- name: Set sbom_tool_path from BESMAN_TOOL_PATH
  set_fact:
    sbom_tool_path: "{{ lookup('env', 'BESMAN_TOOL_PATH') }}"
  when: lookup('env', 'BESMAN_TOOL_PATH') != ''

- name: Check if microsoft sbom-tool file exists
  stat:
    path: "{{ sbom_tool_path }}/sbom-tool-linux-x64"
  register: sbom_file_path

- name: Display message
  debug:
    msg: microsoft sbom-tool is not installed
  when: not sbom_file_path.stat.exists

- name: Removing sbom-tool
  become: yes
  file:
    path: /opt/sbom-tool
    state: absent
  when: sbom_file_path.stat.exists