- name: Set sbom_file_path from BESMAN_TOOL_PATH
  set_fact:
    sbom_tool_path: "{{ lookup('env', 'BESMAN_TOOL_PATH') }}"
  when: lookup('env', 'BESMAN_TOOL_PATH') != ''

- name: Check if microsoft sbom-tool exists
  stat:
    path: "{{ sbom_tool_path }}/sbom-tool-linux-x64"
  register: sbom_file_path

- name: Display file existence status
  debug:
    msg: "microsoft sbom-tool is not installed"
  when: not sbom_file_path.stat.exists

- name: microsft sbom-tool installed
  debug:
    msg: "microsoft sbom-tool is installed"
  when: sbom_file_path.stat.exists